trigger:
  - main
pr:
  branches:
    include:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validate
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: DryRun
        steps:
          - task: Bash@3
            displayName: "Tram Fetch"
            inputs:
              filePath: bin/tram-fetch
            env:
              TRAM_ENTITLEMENT_TOKEN: $(TramEntitlementToken)
          - task: DownloadSecureFile@1
            name: snowflake_key
            displayName: 'Download Snowflake Key File'
            inputs:
              secureFile: 'snowflake_key.p8'
          - task: Bash@3
            displayName: "Tram Dry Run"
            inputs:
              filePath: bin/tram-dry-run
            env:
              TRAM_SNOWFLAKE_URL: '$(TramSnowflakeUrl)$(snowflake_key.secureFilePath)&private_key_file_pwd=$(TramSnowflakePrivKeyPassword)'
              TRAM_SNOWFLAKE_USER: $(TramSnowflakeUser)
              STACK_PATH: stacks/source-product

  - stage: Deploy
    condition: eq(variables['Build.SourceBranchName'], 'main')
    jobs:
      - job: Deploy
        steps:
          - task: Bash@3
            displayName: "Tram Fetch"
            inputs:
              filePath: bin/tram-fetch
            env:
              TRAM_ENTITLEMENT_TOKEN: $(TramEntitlementToken)
          - task: DownloadSecureFile@1
            name: snowflake_key
            displayName: 'Download Snowflake Key File'
            inputs:
              secureFile: 'snowflake_key.p8'
          - task: Bash@3
            displayName: "Tram Provision"
            inputs:
              filePath: bin/tram-provision
            env:
              TRAM_SNOWFLAKE_URL: '$(TramSnowflakeUrl)$(snowflake_key.secureFilePath)&private_key_file_pwd=$(TramSnowflakePrivKeyPassword)'
              TRAM_SNOWFLAKE_USER: $(TramSnowflakeUser)
              STACK_PATH: stacks/source-product