---
destroy: false
entries:
- workspace_name: Toolkit
  username: user1
  access: RO
template:
  engine: JINJA
  path: workspace_access_request.yaml
trigger:
  config:
    maxResults: 1000
    query: "project = IT AND \"Approvals[Approvals]\" = approved() AND status in (\"Waiting for support\") AND \"Request Type\" = \"Request Access To A Snowflake Workspace\" AND createdDate > -14d ORDER BY updatedDate"
  mapping:
    workspace_name: $.fields.customfield_10062.value
    username: $.fields.reporter.emailAddress
    access: $.fields.customfield_10059.value
  primaryKeys:
  - username
  - workspace_name
  removeDomain:
  - username
